### ISSUE TITLE
Shop

### ISSUE THREAD

**Issue by WhySoSerious4** [Central120/uniwork#2]
Table needs design and images currently aren't working.

**Comment by Central120** [comment]
Will fix tomorrow

**Comment by Central120** [comment]
```php
<?php 
$productQuery = mysqli_query($conn, "SELECT * FROM products");

while($row = mysqli_fetch_array($productQuery))
{
     content
}
?>
```

There's the basic code that you'll need in terms of displaying the products you have, as you mentioned last night you want to place them in categories of product types, etc which I told you on how to do so which is to add a WHERE clause in the SQL statement that is selecting everything from the products database table, all you need to add is:

```sql
WHERE category = 'categorytypehere'
```

This will search for all of the records pertaining to that category as it's searching for any product with that category type.

In terms of your table design, as we're using the Bootstrap framework on our website, look at this URL and use this as help to input your table into your code. Ensure that if you're doing so that you close off the PHP after if... { ?> and then place the HTML code so that your page doesn't break, and then after that table html content, re-open the PHP element and close off the while statement with a }.

Bootstrap Tables: https://getbootstrap.com/docs/4.0/content/tables/
